### ISSUE TITLE
easy_install mongoctl doesn't generate default config

### ISSUE THREAD

**Issue by niallo** [mongolab/mongoctl#13]
Since pip install failed on my OS X machine (see #12) I tried `sudo easy_install mongoctl` - which succeeds. However, it doesn't seem to generate a default `~/.mongoctl/mongoctl.config` file:

```
mongoctl connect mongodb://URL
ERROR: Config file /Users/niallo/.mongoctl/mongoctl.config does not exist.
```

My suggestion would be to have mongoctl generate or use the default config at runtime, instead of relying on the presence of on-disk file.

**Comment by abdulito** [comment]
unfortunately we install is only supported by using pip and we don't intend of supporting easy_install. Thanks
