### ISSUE TITLE
How start mongod using --httpinterface --rest with mongoctl?

### ISSUE THREAD

**Issue by AlexZeitler** [mongolab/mongoctl#15]
I tried starting MongoDb using ```mongoctl start --httpinterface --rest REST MyServer``` but I got this error:

    unrecognized arguments: --httpinterface
    Usage: start [<options>] SERVER_ID
    see 'mongoctl start --help' for detailed options

Taking a look at the ```mongoctl``` command reference did not help.

**Comment by abdulito** [comment]
Pushed a fix https://github.com/mongolab/mongoctl/commit/93d05a5aafdc84b1251a00f064f1f16c33e3ab70
