### ISSUE TITLE
mongoctl prefer ssl does not use --ssl in executed command

### ISSUE THREAD

**Issue by chrisckchang** [mongolab/mongoctl#17]
logs:

~ Tue Jan 20 17:18:24 mongoctl --client-ssl-mode prefer connect MONGODB_URI

*************
Will not be using database repository for configurations at this time!
REASON: Could not establish a database connection to mongoctl's database repository.
CAUSE: [Errno 61] Connection refused.
*************
Locating default server for cluster 'MONGODB_URI'...
Connecting to server '......'
Using mongo at '/Users/mongochang/mongodb/mongodb-osx-x86_64-community_ssl-2.6.1/bin/mongo' version '2.6.1 (community_ssl)'...
Executing command: 
/Users/mongochang/mongodb/mongodb-osx-x86_64-community_ssl-2.6.1/bin/mongo dsxxxxx.mongolab.com:xxxx/ssl -u **** -p **** (should use --ssl)
MongoDB shell version: 2.6.1
connecting to: ..........
Error while trying to show server startup warnings: not authorized on admin to execute command { getLog: "startupWarnings" }

**Comment by abdulito** [comment]
Its probably that your server is not running with ssl enabled. Can you check the --sslMode of your mongod?

Thanks

**Comment by abdulito** [comment]
Ah, just realized that it was fixed in https://github.com/mongolab/mongoctl/commit/eae9d509ab633270accc29ed14d6a2be75e1497b

Cheers!
