### ISSUE TITLE
--edition argument in install-mongodb

### ISSUE THREAD

**Issue by pkaeding** [mongolab/mongoctl#23]
I was prompted by an error message to install the community_ssl version, but when I try that, I get the following error about the argument being unrecognized:

```
% mongoctl install-mongodb --edition community_ssl 3.0.5      
unrecognized arguments: --edition 3.0.5
```

I am running mongoctl 0.9.0.

Any ideas?

**Comment by abdulito** [comment]
Hi,

i just tried your same command and it worked for me. Are you sure you are using mongoctl 0.9.0? 
try running

```
mongoctl --version
```

If mongoctl version is 0.9.0 then it could be that one of its dependencies, can you try re-installing mongoctl with pip --force-reinstall?

Cheers!

-abdul
