### ISSUE TITLE
mongoctl does not install with pip-3.2

### ISSUE THREAD

**Issue by duane-unitive** [mongolab/mongoctl#27]
```
# pip-3.2 install mongoctl
Downloading/unpacking mongoctl
  Downloading mongoctl-0.9.0.tar.gz (78Kb): 78Kb downloaded
  Running setup.py egg_info for package mongoctl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/build/mongoctl/setup.py", line 74
        os.chmod(dot_mongoctl_dir, 00755)
                                       ^
    SyntaxError: invalid token
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/build/mongoctl/setup.py", line 74

    os.chmod(dot_mongoctl_dir, 00755)

                                   ^

SyntaxError: invalid token

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /build/mongoctl
```

**Comment by abdulito** [comment]
Hi,

What Python version do you have? Is it 3.0 ? Unfortunately mongoctl is only supported for Pythong 2.6+

**Comment by duane-unitive** [comment]
Yes, this was with 3.0.

only supported for Python 2.6+

I guess, I interpret 3.x to part of the set 2.6+.  :smile:

On Jan 21, 2016, at 8:27 AM, abdulito <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

What Python version do you have? Is it 3.0 ? Unfortunately mongoctl is only supported for Pythong 2.6+

**Comment by abdulito** [comment]
Sorry for not being clear, i meant that its supported for 2.(6+)  2.6 and 2.7 :)

**Comment by duane-unitive** [comment]
Thanks @abdulito. I understood what you meant. Perhaps the documentation should be updated to reflect that python 3.x is not (yet?) supported.
